version: "3.8"

services:
  mongo_db:
    container_name: db_container
    image: mongo
    restart: always
    volumes:
      - mongo_db:/data/db

  frontend:
    build: ./frontend
    ports:
      - 4200:4200
    stdin_open: true

  backend:
    build: ./backend
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo_db/tariff-comparison-docker
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
