version: "3.8"

services:
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    stdin_open: true

  backend:
    build: ./backend
    ports:
      - "3000:3000"

    depends_on:
      - mongodb
